const ACTIONS = {
  SET_RESULTS: 'SET_RESULTS',
  SET_FILTERED_RESULTS: 'SET_FILTERED_RESULTS',
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_ITEMS_COUNT: 'SET_ITEMS_COUNT',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_ITEMS_ON_PAGE: 'SET_ITEMS_ON_PAGE',
} as const;

export default ACTIONS;
